ADVANCED_VOCAB_TOPICS = [
    {
        "name": "🧠 Critical Thinking",
        "legacy_names": ["🧠 C1 Critical Thinking"],
        "description": "C1 vocabulary for analysis, argumentation, and nuanced reasoning",
        "icon_url": "#7C3AED",
        "level": "C1",
        "vocabularies": [
            {"word": "scrutinize", "meaning": "xem xét kỹ lưỡng", "pronunciation": "/ˈskruː.t̬ən.aɪz/", "example_sentence": "The committee will scrutinize the proposal before approving it."},
            {"word": "substantiate", "meaning": "chứng minh, củng cố bằng bằng chứng", "pronunciation": "/səbˈstæn.ʃi.eɪt/", "example_sentence": "Researchers must substantiate their claims with reliable data."},
            {"word": "conjecture", "meaning": "sự phỏng đoán có cơ sở", "pronunciation": "/kənˈdʒek.tʃɚ/", "example_sentence": "His explanation remains conjecture until further evidence emerges."},
            {"word": "discern", "meaning": "nhận ra, phân biệt rõ", "pronunciation": "/dɪˈsɝːn/", "example_sentence": "It is difficult to discern the author's true intention."},
            {"word": "inference", "meaning": "sự suy luận", "pronunciation": "/ˈɪn.fɚ.əns/", "example_sentence": "The inference drawn from the figures was persuasive but incomplete."},
            {"word": "premise", "meaning": "tiền đề", "pronunciation": "/ˈprem.ɪs/", "example_sentence": "The argument rests on a questionable premise."},
            {"word": "paradox", "meaning": "nghịch lý", "pronunciation": "/ˈper.ə.dɑːks/", "example_sentence": "The policy created a paradox: greater choice led to less satisfaction."},
            {"word": "nuance", "meaning": "sắc thái tinh tế", "pronunciation": "/ˈnuː.ɑːns/", "example_sentence": "Her essay captures the nuance of the ethical debate."},
            {"word": "reconcile", "meaning": "hòa giải, dung hòa", "pronunciation": "/ˈrek.ən.saɪl/", "example_sentence": "The report tries to reconcile two opposing interpretations."},
            {"word": "refute", "meaning": "bác bỏ", "pronunciation": "/rɪˈfjuːt/", "example_sentence": "The new evidence refuted the earlier hypothesis."},
            {"word": "ambiguous", "meaning": "mơ hồ, có nhiều cách hiểu", "pronunciation": "/æmˈbɪɡ.ju.əs/", "example_sentence": "The wording of the contract was deliberately ambiguous."},
            {"word": "coherent", "meaning": "mạch lạc, chặt chẽ", "pronunciation": "/koʊˈhɪr.ənt/", "example_sentence": "She presented a coherent account of the historical events."},
            {"word": "contingent", "meaning": "phụ thuộc vào điều kiện", "pronunciation": "/kənˈtɪn.dʒənt/", "example_sentence": "Funding is contingent upon meeting strict performance targets."},
            {"word": "delineate", "meaning": "mô tả, phác họa rõ ràng", "pronunciation": "/dɪˈlɪn.i.eɪt/", "example_sentence": "The speaker delineated the differences between the two theories."},
            {"word": "tenable", "meaning": "có thể bảo vệ được, hợp lý", "pronunciation": "/ˈten.ə.bəl/", "example_sentence": "That position is no longer tenable in light of recent findings."},
        ],
    },
    {
        "name": "🌐 Society & Policy",
        "legacy_names": ["🌐 C1 Society & Policy"],
        "description": "C1 vocabulary for social issues, governance, and public debate",
        "icon_url": "#0F766E",
        "level": "C1",
        "vocabularies": [
            {"word": "marginalize", "meaning": "gạt ra bên lề xã hội", "pronunciation": "/ˈmɑːr.dʒə.nəl.aɪz/", "example_sentence": "The policy may marginalize communities with limited internet access."},
            {"word": "redress", "meaning": "sự bồi thường, sửa chữa bất công", "pronunciation": "/rɪˈdres/", "example_sentence": "The law provides redress for victims of discrimination."},
            {"word": "disparity", "meaning": "sự chênh lệch", "pronunciation": "/dɪˈsper.ə.t̬i/", "example_sentence": "There is a growing disparity between urban and rural incomes."},
            {"word": "accountability", "meaning": "trách nhiệm giải trình", "pronunciation": "/əˌkaʊn.t̬əˈbɪl.ə.t̬i/", "example_sentence": "Public accountability is essential in democratic institutions."},
            {"word": "oversight", "meaning": "sự giám sát", "pronunciation": "/ˈoʊ.vɚ.saɪt/", "example_sentence": "Independent oversight can reduce corruption."},
            {"word": "jurisdiction", "meaning": "thẩm quyền pháp lý", "pronunciation": "/ˌdʒʊr.ɪsˈdɪk.ʃən/", "example_sentence": "The case falls under federal jurisdiction."},
            {"word": "grassroots", "meaning": "từ cơ sở, quần chúng", "pronunciation": "/ˈɡræs.ruːts/", "example_sentence": "The reform began as a grassroots movement."},
            {"word": "polarization", "meaning": "sự phân cực", "pronunciation": "/ˌpoʊ.lɚ.əˈzeɪ.ʃən/", "example_sentence": "Political polarization has intensified public debate."},
            {"word": "legislation", "meaning": "pháp luật, đạo luật", "pronunciation": "/ˌledʒ.əˈsleɪ.ʃən/", "example_sentence": "New legislation aims to protect consumer data."},
            {"word": "dissent", "meaning": "sự bất đồng quan điểm", "pronunciation": "/dɪˈsent/", "example_sentence": "The government tolerated little public dissent."},
            {"word": "advocacy", "meaning": "sự vận động, ủng hộ chính sách", "pronunciation": "/ˈæd.və.kə.si/", "example_sentence": "Her advocacy helped change the national conversation."},
            {"word": "equitable", "meaning": "công bằng", "pronunciation": "/ˈek.wə.t̬ə.bəl/", "example_sentence": "The city needs a more equitable housing policy."},
            {"word": "entitlement", "meaning": "quyền được hưởng", "pronunciation": "/ɪnˈtaɪ.t̬əl.mənt/", "example_sentence": "Healthcare is viewed by many as a basic entitlement."},
            {"word": "incentivize", "meaning": "khuyến khích bằng động lực", "pronunciation": "/ɪnˈsen.t̬ə.vaɪz/", "example_sentence": "Tax breaks can incentivize investment in clean energy."},
            {"word": "bureaucratic", "meaning": "quan liêu, thuộc bộ máy hành chính", "pronunciation": "/ˌbjʊr.əˈkræt̬.ɪk/", "example_sentence": "The application process was slow and bureaucratic."},
        ],
    },
    {
        "name": "⚖️ Legal & Ethical Reasoning",
        "legacy_names": ["⚖️ C2 Legal & Ethical Reasoning"],
        "description": "C2 vocabulary for sophisticated legal, ethical, and philosophical discussion",
        "icon_url": "#991B1B",
        "level": "C2",
        "vocabularies": [
            {"word": "exculpate", "meaning": "minh oan, gỡ tội", "pronunciation": "/ˈek.skʌl.peɪt/", "example_sentence": "The newly discovered footage may exculpate the defendant."},
            {"word": "culpability", "meaning": "trách nhiệm có lỗi", "pronunciation": "/ˌkʌl.pəˈbɪl.ə.t̬i/", "example_sentence": "The court considered his degree of culpability."},
            {"word": "jurisprudence", "meaning": "luật học, triết lý pháp luật", "pronunciation": "/ˌdʒʊr.ɪsˈpruː.dəns/", "example_sentence": "The ruling became a landmark in modern jurisprudence."},
            {"word": "precedent", "meaning": "án lệ, tiền lệ", "pronunciation": "/ˈpres.ə.dent/", "example_sentence": "The decision set a precedent for future privacy cases."},
            {"word": "injunction", "meaning": "lệnh cấm của tòa", "pronunciation": "/ɪnˈdʒʌŋk.ʃən/", "example_sentence": "The company sought an injunction to stop publication."},
            {"word": "fiduciary", "meaning": "người có trách nhiệm ủy thác; thuộc nghĩa vụ ủy thác", "pronunciation": "/fɪˈduː.ʃi.er.i/", "example_sentence": "Board members have fiduciary duties to shareholders."},
            {"word": "proviso", "meaning": "điều khoản ràng buộc", "pronunciation": "/prəˈvaɪ.zoʊ/", "example_sentence": "The agreement included a proviso limiting liability."},
            {"word": "retributive", "meaning": "mang tính trừng phạt báo ứng", "pronunciation": "/rɪˈtruː.bjə.t̬ɪv/", "example_sentence": "The essay challenges retributive theories of punishment."},
            {"word": "deontological", "meaning": "thuộc đạo đức nghĩa vụ luận", "pronunciation": "/ˌdiː.ɑːn.təˈlɑː.dʒɪ.kəl/", "example_sentence": "A deontological view emphasizes duty over consequences."},
            {"word": "teleological", "meaning": "thuộc mục đích luận", "pronunciation": "/ˌtel.i.əˈlɑː.dʒɪ.kəl/", "example_sentence": "The philosopher offered a teleological account of moral action."},
            {"word": "inviolable", "meaning": "bất khả xâm phạm", "pronunciation": "/ɪnˈvaɪ.ə.lə.bəl/", "example_sentence": "The constitution treats certain rights as inviolable."},
            {"word": "abrogate", "meaning": "bãi bỏ, hủy bỏ chính thức", "pronunciation": "/ˈæb.rə.ɡeɪt/", "example_sentence": "Parliament voted to abrogate the outdated treaty."},
            {"word": "tort", "meaning": "hành vi dân sự gây thiệt hại", "pronunciation": "/tɔːrt/", "example_sentence": "Negligence is one of the most common forms of tort."},
            {"word": "mens rea", "meaning": "yếu tố lỗi về mặt tinh thần trong tội phạm", "pronunciation": "/ˌmenz ˈreɪ.ə/", "example_sentence": "Prosecutors must often prove mens rea beyond reasonable doubt."},
            {"word": "equanimity", "meaning": "sự bình thản, điềm tĩnh", "pronunciation": "/ˌek.wəˈnɪm.ə.t̬i/", "example_sentence": "The judge listened to the heated arguments with equanimity."},
        ],
    },
    {
        "name": "🧬 Science & Abstraction",
        "legacy_names": ["🧬 C2 Science & Abstraction"],
        "description": "C2 vocabulary for abstract scientific, academic, and theoretical language",
        "icon_url": "#1D4ED8",
        "level": "C2",
        "vocabularies": [
            {"word": "epistemology", "meaning": "nhận thức luận", "pronunciation": "/ɪˌpɪs.təˈmɑː.lə.dʒi/", "example_sentence": "Epistemology examines how knowledge can be justified."},
            {"word": "ontology", "meaning": "bản thể luận", "pronunciation": "/ɑːnˈtɑː.lə.dʒi/", "example_sentence": "The debate concerns ontology rather than measurement alone."},
            {"word": "heuristic", "meaning": "phương pháp kinh nghiệm để tìm lời giải", "pronunciation": "/hjʊˈrɪs.tɪk/", "example_sentence": "The model uses a heuristic to reduce computational complexity."},
            {"word": "stochastic", "meaning": "ngẫu nhiên, xác suất", "pronunciation": "/stoʊˈkæs.tɪk/", "example_sentence": "Weather patterns are often modeled as stochastic processes."},
            {"word": "isomorphism", "meaning": "sự đẳng cấu", "pronunciation": "/ˌaɪ.səˈmɔːr.fɪ.zəm/", "example_sentence": "The proof demonstrates an isomorphism between the two structures."},
            {"word": "axiomatic", "meaning": "mang tính tiên đề", "pronunciation": "/ˌæk.si.əˈmæt̬.ɪk/", "example_sentence": "The theory begins with several axiomatic assumptions."},
            {"word": "reductionism", "meaning": "thuyết giản lược", "pronunciation": "/rɪˈdʌk.ʃən.ɪ.zəm/", "example_sentence": "Critics argue that strict reductionism overlooks emergent behavior."},
            {"word": "emergent", "meaning": "nổi lên từ hệ phức tạp", "pronunciation": "/ɪˈmɝː.dʒənt/", "example_sentence": "Consciousness may be an emergent property of neural systems."},
            {"word": "entropic", "meaning": "thuộc entropy, có xu hướng hỗn loạn", "pronunciation": "/enˈtrɑː.pɪk/", "example_sentence": "The system becomes increasingly entropic without external input."},
            {"word": "taxonomic", "meaning": "thuộc phân loại học", "pronunciation": "/ˌtæk.səˈnɑː.mɪk/", "example_sentence": "The database uses a taxonomic hierarchy to organize species."},
            {"word": "liminality", "meaning": "trạng thái ngưỡng, chuyển tiếp", "pronunciation": "/ˌlɪm.əˈnæl.ə.t̬i/", "example_sentence": "The study explores liminality in rites of passage."},
            {"word": "paradigmatic", "meaning": "mang tính mô hình, hệ hình", "pronunciation": "/ˌper.ə.daɪɡˈmæt̬.ɪk/", "example_sentence": "The discovery caused a paradigmatic shift in the field."},
            {"word": "phenomenology", "meaning": "hiện tượng học", "pronunciation": "/fəˌnɑː.məˈnɑː.lə.dʒi/", "example_sentence": "Phenomenology focuses on lived experience and perception."},
            {"word": "dialectical", "meaning": "biện chứng", "pronunciation": "/ˌdaɪ.əˈlek.tɪ.kəl/", "example_sentence": "The argument develops through a dialectical exchange of opposing views."},
            {"word": "metacognition", "meaning": "siêu nhận thức", "pronunciation": "/ˌmet̬.ə.kɑːɡˈnɪʃ.ən/", "example_sentence": "Metacognition helps learners monitor and adjust their strategies."},
        ],
    },
    {
        "name": "💼 Business & Negotiation",
        "legacy_names": ["💼 B2 Business & Negotiation"],
        "description": "B2 vocabulary for business communication, planning, and negotiation",
        "icon_url": "#D97706",
        "level": "B2",
        "vocabularies": [
            {"word": "stakeholder", "meaning": "bên liên quan", "pronunciation": "/ˈsteɪkˌhoʊl.dɚ/", "example_sentence": "Every stakeholder should be informed before the launch."},
            {"word": "benchmark", "meaning": "chuẩn để so sánh", "pronunciation": "/ˈbentʃ.mɑːrk/", "example_sentence": "We used last year's results as a benchmark."},
            {"word": "revenue", "meaning": "doanh thu", "pronunciation": "/ˈrev.ə.nuː/", "example_sentence": "The company increased its revenue in the second quarter."},
            {"word": "forecast", "meaning": "dự báo", "pronunciation": "/ˈfɔːr.kæst/", "example_sentence": "The sales forecast looks positive for next month."},
            {"word": "proposal", "meaning": "đề xuất", "pronunciation": "/prəˈpoʊ.zəl/", "example_sentence": "The client accepted our proposal after two meetings."},
            {"word": "compromise", "meaning": "sự thỏa hiệp", "pronunciation": "/ˈkɑːm.prə.maɪz/", "example_sentence": "A fair compromise helped both teams move forward."},
            {"word": "leverage", "meaning": "tận dụng lợi thế", "pronunciation": "/ˈlev.ɚ.ɪdʒ/", "example_sentence": "We can leverage our network to find new partners."},
            {"word": "contingency", "meaning": "phương án dự phòng", "pronunciation": "/kənˈtɪn.dʒən.si/", "example_sentence": "The team prepared a contingency plan for delays."},
            {"word": "procurement", "meaning": "việc mua sắm, thu mua", "pronunciation": "/prəˈkjʊr.mənt/", "example_sentence": "Procurement costs rose because of supply shortages."},
            {"word": "retention", "meaning": "sự giữ chân", "pronunciation": "/rɪˈten.ʃən/", "example_sentence": "Employee retention improved after the new training program."},
            {"word": "turnover", "meaning": "tỷ lệ thay nhân sự; doanh số", "pronunciation": "/ˈtɝːnˌoʊ.vɚ/", "example_sentence": "High staff turnover can damage team morale."},
            {"word": "liability", "meaning": "trách nhiệm pháp lý, khoản nợ", "pronunciation": "/ˌlaɪ.əˈbɪl.ə.t̬i/", "example_sentence": "The contract limits the supplier's liability."},
            {"word": "margin", "meaning": "biên lợi nhuận", "pronunciation": "/ˈmɑːr.dʒɪn/", "example_sentence": "The profit margin is smaller than expected."},
            {"word": "deliverable", "meaning": "sản phẩm bàn giao", "pronunciation": "/dɪˈlɪv.ɚ.ə.bəl/", "example_sentence": "Each deliverable must be submitted by Friday."},
            {"word": "constraint", "meaning": "sự ràng buộc, hạn chế", "pronunciation": "/kənˈstreɪnt/", "example_sentence": "Budget constraints forced us to change the timeline."},
        ],
    },
]


def audio_slug(word: str) -> str:
    return word.replace(" ", "_").replace("-", "_").lower()
